api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    eager_loading:
        enabled: true
    collection:
        pagination:
#            enabled: false
#            kann auch unter apiREsource eingetragen werden pagination_enabled: false ili pagination_client_enabled
#            page_parameter_name: _page
#            client kann pagination=false schreiben
#            client_enabled: true
#            enabled_parameter_name: pagination
            items_per_page: 4



