easy_admin:
    entities:
        # List the entity class name you want to manage
        User:
            class: App\Entity\User
            controller: App\Controller\UserAdminController
        Comment:
            class: App\Entity\Comment
        BlogPost:
            class: App\Entity\BlogPost
        Image:
            class: App\Entity\Image
#        - App\Entity\Comment
#        - App\Entity\BlogPost
#        - App\Entity\Image
